import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Bot, Check, ChevronRight, Landmark, LockKeyhole, Play, ShieldCheck, TrendingUp, Trophy, WalletCards } from "lucide-react";
import { Brand } from "@/components/brand";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head:()=>({meta:[{title:'FinQuest — Learn Finance by Living It'},{name:'description',content:'Master banking, investing, budgeting and fraud prevention through AI-powered simulations.'},{property:'og:title',content:'FinQuest — Learn Finance by Living It'},{property:'og:description',content:'A risk-free world where every money decision teaches you something.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),
  component: Index,
});

function Index() {
  return <div className="min-h-screen overflow-hidden bg-background text-foreground">
   <header className="fixed inset-x-0 top-0 z-50 border-b border-border/70 bg-background/75 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 md:px-8"><Brand/><nav className="hidden items-center gap-7 text-xs text-muted-foreground md:flex"><a href="#experience" className="hover:text-foreground">Experience</a><a href="#journey" className="hover:text-foreground">Journey</a><a href="#stories" className="hover:text-foreground">Stories</a></nav><div className="flex items-center gap-2"><Button variant="ghost" asChild><Link to="/auth">Log in</Link></Button><Button variant="hero" asChild><Link to="/auth">Start learning<ArrowRight/></Link></Button></div></div></header>
   <main><section className="hero-grid relative mx-auto flex min-h-[92vh] max-w-7xl items-center px-4 pb-16 pt-28 md:px-8"><div className="relative z-10 max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-xs text-primary"><span className="size-1.5 rounded-full bg-success animate-pulse"/>Your risk-free money playground</div><h1 className="max-w-4xl text-5xl font-semibold leading-[1.03] md:text-7xl lg:text-8xl">Learn Finance<br/>by <span className="text-gradient">Living It.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground md:text-lg">Master banking, investing, budgeting and fraud prevention through AI-powered simulations.</p><div className="mt-8 flex flex-wrap gap-3"><Button variant="hero" size="lg" asChild><Link to="/auth"><Play/>Start Learning</Link></Button><Button variant="glass" size="lg" asChild><Link to="/market">Explore simulator<ChevronRight/></Link></Button></div><div className="mt-10 flex flex-wrap gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><Check className="size-3.5 text-success"/>No real money</span><span className="flex items-center gap-2"><Check className="size-3.5 text-success"/>AI feedback</span><span className="flex items-center gap-2"><Check className="size-3.5 text-success"/>Built for India</span></div></div><div className="hero-orbit hidden lg:block"><div className="market-card glass-card"><div className="flex justify-between"><span className="text-xs text-muted-foreground">Virtual portfolio</span><TrendingUp className="size-4 text-success"/></div><p className="mt-4 text-3xl font-semibold">₹1,24,860</p><p className="text-xs text-success">+8.42% all time</p><div className="mt-6 flex h-24 items-end gap-1">{[32,48,39,61,52,76,68,88,79,96].map((h,i)=><span key={i} className="flex-1 rounded-t bg-primary/60" style={{height:`${h}%`}}/>)}</div></div><div className="floating-chip chip-xp"><Trophy/>+120 XP</div><div className="floating-chip chip-safe"><ShieldCheck/>Fraud blocked</div></div></section>
   <section className="border-y border-border bg-card/30"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-border px-4 md:grid-cols-4 md:px-8">{[['50K+','learners'],['2.4M','decisions simulated'],['91%','feel money-confident'],['11','skill quests']].map(x=><div className="py-8 text-center" key={x[1]}><p className="text-2xl font-semibold md:text-3xl">{x[0]}</p><p className="mt-1 text-[11px] uppercase tracking-[.12em] text-muted-foreground">{x[1]}</p></div>)}</div></section>
   <section id="experience" className="mx-auto max-w-7xl px-4 py-24 md:px-8"><p className="section-kicker">Practice beats theory</p><div className="mt-3 grid gap-8 lg:grid-cols-2"><h2 className="text-3xl font-semibold md:text-5xl">Make the mistakes here.<br/>Keep the wisdom forever.</h2><p className="max-w-xl text-sm leading-7 text-muted-foreground">Every quest puts you inside a real financial moment. Choose, see the consequence, and get an explanation that adapts to your level.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{[[TrendingUp,'Market Lab','Trade through earnings, inflation and global events with ₹10 lakh in virtual cash.'],[LockKeyhole,'Fraud Lab','Face realistic UPI, QR, OTP, phishing and investment scams safely.'],[Bot,'AI Mentor','Ask anything in plain language and get guidance shaped around your goal.']].map(([Icon,t,d])=><article className="glass-card group min-h-64 p-6" key={String(t)}><div className="module-icon module-violet"><Icon/></div><h3 className="mt-16 text-xl font-semibold">{String(t)}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{String(d)}</p></article>)}</div></section>
   <section id="journey" className="border-y border-border bg-card/30"><div className="mx-auto max-w-7xl px-4 py-24 md:px-8"><div className="max-w-xl"><p className="section-kicker">Your financial journey</p><h2 className="mt-3 text-3xl font-semibold md:text-5xl">A roadmap that grows with you.</h2></div><div className="mt-12 grid gap-3 lg:grid-cols-4">{[['01','Choose your goal','Student, first job, investor, family, or business.'],['02','Learn the move','Short visual lessons, never long lectures.'],['03','Test the decision','Simulate the pressure without risking a rupee.'],['04','Level up','Earn XP, unlock challenges, and prove your skills.']].map(x=><div className="border-l border-primary/40 p-5" key={x[0]}><span className="font-mono text-xs text-primary">{x[0]}</span><h3 className="mt-8 font-semibold">{x[1]}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{x[2]}</p></div>)}</div></div></section>
   <section id="stories" className="mx-auto max-w-7xl px-4 py-24 md:px-8"><div className="text-center"><p className="section-kicker">Confidence, unlocked</p><h2 className="mt-3 text-3xl font-semibold">Built for your first real money decisions.</h2></div><div className="mx-auto mt-10 grid max-w-5xl gap-4 md:grid-cols-3">{[['Aarav, 19','“I finally understood why an emergency fund comes before investing.”'],['Meera, 23','“The scam scenarios feel real. My parents now ask me before scanning a QR.”'],['Karan, 26','“Market Lab taught me more about risk than months of watching reels.”']].map(x=><figure className="glass-card p-6" key={x[0]}><blockquote className="text-sm leading-6">{x[1]}</blockquote><figcaption className="mt-6 text-xs text-primary">{x[0]}</figcaption></figure>)}</div></section>
   <section className="mx-4 mb-8 overflow-hidden rounded-xl border border-primary/20 bg-hero px-6 py-16 text-center md:mx-8"><Landmark className="mx-auto size-8 text-primary"/><h2 className="mt-5 text-3xl font-semibold md:text-5xl">Your first quest starts now.</h2><p className="mx-auto mt-3 max-w-lg text-sm text-muted-foreground">Practice decisions today that your future self will thank you for.</p><Button className="mt-7" variant="hero" size="lg" asChild><Link to="/auth">Start learning free<ArrowRight/></Link></Button></section></main>
   <footer className="border-t border-border"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-8 text-xs text-muted-foreground md:flex-row md:items-center md:justify-between md:px-8"><Brand/><p>© 2026 FinQuest. Learn safely. Decide confidently.</p><div className="flex gap-5"><span>Privacy</span><span>Terms</span><span>Support</span></div></div></footer>
  </div>;
}
