import { Link } from '@tanstack/react-router';
import { ArrowRight, Award, BookOpen, CheckCircle2, ChevronRight, Coins, Flame, Play, Trophy, Zap } from 'lucide-react';
import { AppShell } from './app-shell';
import { Button } from './ui/button';
import { modules } from '@/lib/finquest-data';
export function DashboardContent(){return <AppShell title="Good evening, Taran" eyebrow="Friday, 18 September">
 <section className="relative overflow-hidden rounded-xl border border-primary/20 bg-hero p-6 md:p-9"><div className="relative z-10 max-w-2xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-accent/30 bg-accent/10 px-3 py-1 text-xs text-accent"><Flame className="size-3.5"/>7 day learning streak</div><h2 className="text-3xl font-semibold leading-tight md:text-5xl">Your money skills are<br/><span className="text-gradient">compounding.</span></h2><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">Complete today’s lesson to reach Level 5 and unlock the SIP simulator.</p><div className="mt-6 flex flex-wrap items-center gap-3"><Button size="lg" asChild><Link to="/learn"><Play/>Continue learning</Link></Button><span className="text-xs text-muted-foreground">12 min · UPI Safety</span></div></div><div className="absolute -right-8 -bottom-16 hidden size-72 rounded-full border-[40px] border-primary/10 md:block"/></section>
 <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Zap,'1,240','Total XP','+180 this week'],[Coins,'480','Quest coins','+45 today'],[Trophy,'#128','India rank','↑ 24 places'],[Award,'68%','Level progress','260 XP to go']].map(([Icon,v,l,s])=><div className="glass-card p-4" key={String(l)}><div className="flex items-start justify-between"><div className="grid size-9 place-items-center rounded-md bg-primary/10 text-primary"><Icon className="size-4"/></div><span className="text-[11px] text-success">{String(s)}</span></div><p className="mt-5 text-2xl font-semibold">{String(v)}</p><p className="text-xs text-muted-foreground">{String(l)}</p></div>)}</div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_.8fr]"><section className="glass-card p-5 md:p-6"><div className="flex items-center justify-between"><div><p className="section-kicker">Learning path</p><h3 className="mt-1 text-xl font-semibold">Your next quests</h3></div><Button variant="ghost" asChild><Link to="/learn">View path<ArrowRight/></Link></Button></div><div className="mt-5 space-y-3">{modules.slice(0,3).map((m,i)=><Link to="/learn" key={m.slug} className="group flex items-center gap-4 rounded-lg border border-border bg-background/35 p-4 transition hover:border-primary/40"><div className={`module-icon module-${m.color}`}><m.icon/></div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="truncate text-sm font-medium">{m.title}</p><span className="text-xs text-muted-foreground">{m.progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-gradient-brand" style={{width:`${m.progress}%`}}/></div></div>{i===0?<CheckCircle2 className="size-5 text-success"/>:<ChevronRight className="size-5 text-muted-foreground transition group-hover:translate-x-1"/>}</Link>)}</div></section>
 <section className="glass-card p-5 md:p-6"><p className="section-kicker">Weekly performance</p><div className="mt-6 flex h-40 items-end justify-between gap-2">{[42,58,35,78,62,92,54].map((h,i)=><div key={i} className="flex h-full flex-1 flex-col justify-end gap-2"><div className={`rounded-t-sm ${i===5?'bg-gradient-brand':'bg-muted'}`} style={{height:`${h}%`}}/><span className="text-center text-[10px] text-muted-foreground">{['M','T','W','T','F','S','S'][i]}</span></div>)}</div><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><div><p className="text-2xl font-semibold">84%</p><p className="text-xs text-muted-foreground">Quiz accuracy</p></div><div className="text-right"><p className="text-sm font-medium text-success">+12%</p><p className="text-xs text-muted-foreground">vs last week</p></div></div></section></div>
 <section className="mt-5"><div className="mb-4 flex items-end justify-between"><div><p className="section-kicker">Daily challenges</p><h3 className="mt-1 text-xl font-semibold">Three ways to earn today</h3></div><BookOpen className="text-primary"/></div><div className="grid gap-4 md:grid-cols-3">{[['Spot the scam','Identify the fake UPI request','+40 XP'],['Budget sprint','Balance a ₹35,000 salary','+60 XP'],['Market pulse','React to an earnings surprise','+80 XP']].map((x,i)=><Link to={i===0?'/fraud-lab':i===1?'/finance-lab':'/market'} className="glass-card group p-5 hover:-translate-y-1" key={x[0]}><span className="text-xs text-primary">0{i+1}</span><h4 className="mt-6 font-semibold">{x[0]}</h4><p className="mt-1 text-xs text-muted-foreground">{x[1]}</p><div className="mt-5 flex items-center justify-between"><span className="text-xs font-medium text-accent">{x[2]}</span><ArrowRight className="size-4 transition group-hover:translate-x-1"/></div></Link>)}</div></section>
 </AppShell>}
